### PR TITLE
Option to overwrite template

### PR DESCRIPTION
**Pull request by bitte-ein-bit**
We needed an option to overwrite the template since we are using an internal mirror. This seemed the most appropriate way.

### CODE REVIEW

**Comment by andyleejordan** [comment]
Looks fine.

**Comment by andyleejordan** [comment]
@bitte-ein-bit can you test master and let me know if I should push a release?

**Comment by bitte-ein-bit** [comment]
Looks good to me. A new release would really be nice.

**Comment by bitte-ein-bit** [comment]
Could you do a new release please?

**Comment by bitte-ein-bit** [comment]
@andschwa not sure if you're watching. Could you do a new release please?

**Comment by poolski** [comment]
@bitte-ein-bit done :)

**Comment by andyleejordan** [comment]
Thanks @poolski :smile:

**Pull request merged**
